using DataLayer.Database;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Linq;
using System.Collections.Generic;
using System;
using System.Linq;
using Welcome.Model;

namespace DataLayer.Model
{
   public class DatabaseUser : User
    {
        [Key] // Marks `id` property as key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Autogenerated
        public override int Id { get; set; }

        public static void InsertUser(DatabaseContext context, string name, string pass, UserType role, DateTime expires)
        {
            context.Add<DatabaseUser>(new DatabaseUser()
            {
                Name = name,
                Password = pass,
                Role = role,
                Expires = expires
            });
            context.SaveChanges();
        } // InsertUser()

        public static List<DatabaseUser> GetAllUsers(DatabaseContext context)
        {
            return context.Users.ToList();
        } // GetAllUsers()

        public static void InsertUserFromConsole(DatabaseContext context, string name, string pass)
        {
            context.Add<DatabaseUser>(new DatabaseUser()
            {
                Name = name,
                Password = pass,
                Role = UserType.Moderator,
                Expires = DateTime.Now
            });
            context.SaveChanges();
        } // InsertUserFromConsole()

        public static void DeleteUserByName(DatabaseContext context, string name)
        {
            var user = context.Users.FirstOrDefault(u => u.Name == name);
            if (user != null)
            {
                context.Users.Remove(user);
                context.SaveChanges();
            }
        } // DeleteUserByName()
    }
}
